services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo_val:/data/db
    networks:
      - app_network
    ports:
      - 27017:27017

  backend:
    build:
      context: ./server/Dockerfile.dev
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongodb:27017/teapostv3
    env_file:
      - ./server/.env
    ports:
      - 4000:4000
    command: npm run dev
    volumes:
      - ./server/:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app_network

  client:
    build:
      context: ./client
      target: dev
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/teapostv3
      - NODE_ENV=development
    env_file:
      - ./client/.env

    command: npm run dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000

    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mongo_val:

networks:
  app_network:
    driver: bridge
