services:
  mongodb:
    image: imsamad/teapostv2_nginx:1.0.0
    volumes:
      - mongo_val:/data/db
    networks:
      - app_network

  backend:
    image: imsamad/teapostv2_backend:1.0.0
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongodb:27017/teapost
    env_file:
      - ./server/.env
    command: npm start
    depends_on:
      - mongodb
    networks:
      - app_network

  client:
    image: imsamad/teapostv2_client:1.0.0
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/teapost
    env_file:
      - ./client/.env

    depends_on:
      - backend
    networks:
      - app_network

  nginx:
    image: imsamad/teapostv2_nginx:1.0.0
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mongo_val:

networks:
  app_network:
    driver: bridge
