"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.forgotIdentifier = exports.confirmChangedEmail = exports.changeEmail = exports.resetPassword = exports.forgotPassword = exports.login = exports.confirmRegistration = exports.register = void 0;
const register_1 = __importDefault(require("./register"));
exports.register = register_1.default;
const confirmRegistration_1 = __importDefault(require("./confirmRegistration"));
exports.confirmRegistration = confirmRegistration_1.default;
const login_1 = __importDefault(require("./login"));
exports.login = login_1.default;
const forgotPassword_1 = __importDefault(require("./forgotPassword"));
exports.forgotPassword = forgotPassword_1.default;
const resetPassword_1 = __importDefault(require("./resetPassword"));
exports.resetPassword = resetPassword_1.default;
const changeEmail_1 = __importDefault(require("./changeEmail"));
exports.changeEmail = changeEmail_1.default;
const confirmChangedEmail_1 = __importDefault(require("./confirmChangedEmail"));
exports.confirmChangedEmail = confirmChangedEmail_1.default;
const forgotIdentifier_1 = __importDefault(require("./forgotIdentifier"));
exports.forgotIdentifier = forgotIdentifier_1.default;
