FROM node:20.11.1-alpine AS base

FROM base as deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . . 
CMD npm run dev

FROM base as prod
WORKDIR /app
COPY --from=deps /app/node_modules /node_modules
COPY . . 
RUN npm run build
CMD npm start