FROM node:20.11-alpine as base
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm ci
COPY . .

FROM base as dev
COPY . .
CMD npm run dev

FROM base as prod
COPY . .
RUN npm run build
CMD npm start

